### ISSUE TITLE
Feature: Keep Unreleased Section

### ISSUE THREAD

**Issue by bryannielsen** [release-flow/keep-a-changelog-action#36]
Thanks for making this action!  It has been really helpful in my workflows.

I was wondering if it would be possible to have an option to create a new 'Unreleased' section at the top of the changelog after running the prepare-release action.

**Comment by richtea** [comment]
Thanks very much Bryan, glad you're finding it useful! I've actually thought about this feature before, and I think it's a great idea. If you want to send a PR that would be great - if not, I'll look into it once I've finished my current refactoring into two repos (the GitHub recommendation is to have a single action per repo).

**Comment by bryannielsen** [comment]
That sounds great!  I don't have any experience with TypeScript but I can try to poke around and see if it's something I can figure out.  I was thinking about this a little more and along with automatically adding the 'Unreleased' section it might be nice to add some checks so that preparing a release with an empty 'Unreleased' section throws an error.  I know that if the section is missing it errors but I'm not sure if it complains when it's empty.

**Comment by richtea** [comment]
Actually, I've started work on this myself now, it's a bit WIP right now but I'll post here when I launch a beta. You may have noticed that V2 is now available - no functional changes, but it combines both the earlier actions into a single action with subcommands. I wanted to get that launched before moving onto this. 

I really like the warning idea for empty `Unreleased` section - I'll look to build that in.

**Comment by bryannielsen** [comment]
Thanks for doing this! 
I just got around to updating to the new action and made use of the parameter and it works perfectly!

**Comment by richtea** [comment]
Glad you like it @bryannielsen ! I've also done the other change you asked for, available in release 2.2.0
